### ISSUE TITLE
При смене темы местами меняется цвет текста

### ISSUE THREAD

**Issue by juyka** [AnikoV/RatingVolsuWP8#5]
В некоторых местах нужно указать именно белый цвет, чтобы он не менялся при смене темы
![wp_ss_20140618_0001](https://cloud.githubusercontent.com/assets/6871589/3312597/1fec6226-f6d5-11e3-9121-c99131341850.png)

**Comment by AnikoV** [comment]
не воспроизводится
![bug](https://cloud.githubusercontent.com/assets/3219118/3351901/cb712f08-fa24-11e3-8b4a-84a13d332d9a.png)
