### ISSUE TITLE
Не отображаются места в рейтинге

### ISSUE THREAD

**Issue by juyka** [AnikoV/RatingVolsuWP8#6]
Когда данные загрузились с бд, а с сервера только началась загрузка, цифры не отображаются. они появляются только после того,  как закончится загрузка с сервера.
![fsfrg](https://cloud.githubusercontent.com/assets/6871589/3479943/ea98fc56-0359-11e4-9794-0c3717c182c5.png)

**Comment by AnikoV** [comment]
пока не могу понять в чем дело - когда достаем рейтинг из БДхи, то не срабатывает конвертер значений при изменении RatingCollectionForView, а когда из веба тянем, то все окей и срабатывает конвертер. Хотя значения ложатся одни и теже

**Comment by AnikoV** [comment]
поправлено
