### ISSUE TITLE
Не помещается статистика

### ISSUE THREAD

**Issue by juyka** [AnikoV/RatingVolsuWP8#9]
Теперь во всех предметах появились трехзначные числа, надо как то это выровнять
![kjnh](https://cloud.githubusercontent.com/assets/6871589/3480044/46ead834-035b-11e4-8ccb-b9d25d5286dd.png)

**Comment by AnikoV** [comment]
ааа, это типо все предметы?

**Comment by AnikoV** [comment]
Поправил, посмотри, если все ок, то закрой баг
